---
- name: install tomcat
  hosts: all
  become: yes

  tasks:

  - name: Ensure tomcat package is present
    apt:
      name: tomcat
      status: present

  - name: Ensure tomcat service is started
    service:
      name: tomcat
      status: started

- name: install jdk
  hosts: all
  become: yes

  tasks:

  - name: Ensure jdk package is present
    apt:
      name: default-jdk
      status: present




