---
- name: install java related packages
  hosts: all
  become: yes

  tasks:

  - name: Ensure java related packages are present
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - openjdk-8-jdk
        - tomcat9

  - name: Ensure tomcat service is started
    service:
      name: tomcat9
      state: started

- name: install maven, download and pack java app
  hosts: maven
  become: yes

  tasks:

  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: Ensure git package is present
    apt:
      name: git
      state: present

  - name: Download java app
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/xopco/boxfuse-sample-java-war-hello

  - name: pack java app
    shell: mvn package
    args:
      chdir: /home/xopco/boxfuse-sample-java-war-hello

- name: copy java app on web server
  hosts: all
  become: yes

  tasks:

  - name: copy artifact to master
    fetch:
      src: /home/xopco/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /tmp/hello-1.0.war

  - name: copy artifact to web-server
    copy:
      src: localhost:/tmp/hello-1.0.war
      dest: prod:/var/lib/tomcat9/webapps
...








