---
- name: install java related packages
  hosts: all
  become: yes

  tasks:

  - name: Ensure java related packages are present
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - openjdk-8-jdk
        - tomcat9

  - name: Ensure tomcat service is started
    service:
      name: tomcat9
      state: started

- name: install maven, download and pack java app
  hosts: maven
  become: yes

  tasks:

  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: Ensure git package is present
    apt:
      name: git
      state: present

  - name: Download java app
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/xopco/boxfuse-sample-java-war-hello

  - name: pack java app
    shell: mvn package "/home/xopco/boxfuse-sample-java-war-hello/pom.xml"

- name: copy java app on web server
  hosts: prod

  tasks:

  - name: copy artifact to tomcat dest
    copy:
      src: maven:/home/xopco/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/hello-1.0.war
...








