---
# tasks file for webserver
- name: get artifact from build
  synchronize:
    src: "{{ rem_src }}" hello-1.0.war
    dest: "{{ dest_folder }}"
  delegate_to: localhost
  notify:
    - restart tomcat